Try to fix angular errors
I'm doing this cuz I get the following in azure pipelines when trying to deploy to azure:

ERROR in src/app/site-detail/site-detail.component.html(36,17): Property 'totalOnSolarEnergyConsumption' does not exist on type 'ConsumptionTotal'.
src/app/site-detail/site-detail.component.html(37,17): Property 'totalOffSolarEnergyConsumption' does not exist on type 'ConsumptionTotal'.
src/app/consumption/consumption.component.html(9,33): Property 'addAppliance' does not exist on type 'ConsumptionComponent'.